// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPYFd_H5YKoGk1UFLspmZsz-zZ_smKBcE',
    appId: '1:634564775821:web:7afe1eafd8a2f41babf7c4',
    messagingSenderId: '634564775821',
    projectId: 'flutter-demo-a7257',
    authDomain: 'flutter-demo-a7257.firebaseapp.com',
    databaseURL: 'https://flutter-demo-a7257-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-a7257.appspot.com',
    measurementId: 'G-EH7BXJ3D5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDfXB0h143qrxBFXycD7QAU0q7DxjGbyQ',
    appId: '1:634564775821:android:a02af0d675b34a74abf7c4',
    messagingSenderId: '634564775821',
    projectId: 'flutter-demo-a7257',
    databaseURL: 'https://flutter-demo-a7257-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-a7257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1QydN_4WE_q9MvQIX-RVKljiJd2cylg',
    appId: '1:634564775821:ios:8811b00312973b36abf7c4',
    messagingSenderId: '634564775821',
    projectId: 'flutter-demo-a7257',
    databaseURL: 'https://flutter-demo-a7257-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-a7257.appspot.com',
    iosClientId: '634564775821-bht744loj6l5bp9b4j1r48s1vj0vngjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter060FirebaseDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS1QydN_4WE_q9MvQIX-RVKljiJd2cylg',
    appId: '1:634564775821:ios:8811b00312973b36abf7c4',
    messagingSenderId: '634564775821',
    projectId: 'flutter-demo-a7257',
    databaseURL: 'https://flutter-demo-a7257-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-a7257.appspot.com',
    iosClientId: '634564775821-bht744loj6l5bp9b4j1r48s1vj0vngjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter060FirebaseDb',
  );
}
